// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aredhlxedhvfnoizborq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyZWRobHhlZGh2Zm5vaXpib3JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjMzNzEsImV4cCI6MjA1OTY5OTM3MX0.vdn0bzABFGnZYR9l3SghJjx7dIFZ7vFT8FkqTLHaeFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);